-- MySQL Script generated by MySQL Workbench
-- Mon May 20 19:27:54 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema demo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema demo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `demo` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `demo` ;

-- -----------------------------------------------------
-- Table `demo`.`summary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo`.`summary` (
  `Month` VARCHAR(50) NOT NULL,
  `totalEX` INT(11) NOT NULL,
  `totalRe` INT(11) NOT NULL,
  `initBalance` INT(11) NOT NULL,
  PRIMARY KEY (`Month`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `demo`.`tblchi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo`.`tblchi` (
  `date` DATE NOT NULL,
  `MSNV` VARCHAR(8) NOT NULL,
  `empolyees` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `category` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `purpose` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `price` INT(11) NOT NULL,
  PRIMARY KEY (`date`, `MSNV`, `purpose`, `category`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `demo`.`tblthu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo`.`tblthu` (
  `date` DATE NOT NULL,
  `revenues` VARCHAR(45) NOT NULL,
  `category` VARCHAR(20) NOT NULL,
  `purpose` VARCHAR(200) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`date`, `revenues`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `demo`.`usersaccount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo`.`usersaccount` (
  `msnv` VARCHAR(8) NOT NULL,
  `password` VARCHAR(8) NOT NULL,
  `userName` VARCHAR(30) NOT NULL,
  `office` VARCHAR(10) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `salary` INT(11) NOT NULL,
  `image` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`msnv`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `demo`.`usersfamily`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo`.`usersfamily` (
  `msnv` VARCHAR(8) NOT NULL,
  `userFamily` VARCHAR(30) NULL DEFAULT NULL,
  `birthFamily` DATE NULL DEFAULT NULL,
  `jobFamily` VARCHAR(45) NULL DEFAULT NULL,
  `phoneFamily` VARCHAR(12) NULL DEFAULT NULL,
  `child` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`msnv`),
  CONSTRAINT `family_fk_info`
    FOREIGN KEY (`msnv`)
    REFERENCES `demo`.`usersaccount` (`msnv`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `demo`.`usersinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo`.`usersinfo` (
  `msnv` VARCHAR(8) NOT NULL,
  `birthday` DATE NULL DEFAULT NULL,
  `gender` VARCHAR(10) NULL DEFAULT NULL,
  `numberPhone` VARCHAR(12) NULL DEFAULT NULL,
  `nationality` MEDIUMTEXT NULL DEFAULT NULL,
  `nation` VARCHAR(20) NULL DEFAULT NULL,
  `religion` VARCHAR(45) NULL DEFAULT NULL,
  `cmnd` VARCHAR(20) NULL DEFAULT NULL,
  `range` DATE NULL DEFAULT NULL,
  `issued` VARCHAR(45) NULL DEFAULT NULL,
  `address1` MEDIUMTEXT NULL DEFAULT NULL,
  `address2` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`msnv`),
  CONSTRAINT `info_fk_user`
    FOREIGN KEY (`msnv`)
    REFERENCES `demo`.`usersaccount` (`msnv`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
